#!/bin/sh

case "$1" in
	start)
		printf "insmod NPU modules: "
		cp /usr/lib/cl_*.h /tmp/
		insmod /usr/lib/modules/galcore.ko contiguousSize=0x400000 gpuProfiler=1
		echo 792000000 > /sys/class/devfreq/ffbc0000.npu/userspace/set_freq
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		start_usb.sh ntb
		;;
	stop)
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit 0
