#!/bin/sh

case "$1" in
	start)
		printf "insmod NPU modules: "
		insmod /lib/modules/rknpu.ko
		unset MAX_FREQ
		read  MAX_FREQ < /sys/class/devfreq/fde40000.npu/max_freq
		echo  $MAX_FREQ > /sys/class/devfreq/fde40000.npu/userspace/set_freq
		[ $? = 0 ] && echo "OK" || echo "FAIL"
#start_rknn.sh &
		;;
	stop)
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit 0
